version: "3.8"
services:
  web:
    build: .
    command: >
      sh -c "alembic revision --autogenerate -m 'docker-compose bulid' && \
             alembic upgrade head && \
             uvicorn main:app --host 0.0.0.0 --port 8000"

    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: psy_test
      POSTGRES_USER: samiiz
      POSTGRES_PASSWORD: Parkshghfh9801!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
