version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://samiiz:p0105samiiz@db:5432/psytest
    command: >
      sh -c "python3 main.py"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: psytest
      POSTGRES_USER: samiiz
      POSTGRES_PASSWORD: p0105samiiz
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
