"""docker-compose bulid

Revision ID: 2caa9f71e350
Revises: bd2f1bb84d55
Create Date: 2024-03-24 22:01:55.878659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2caa9f71e350'
down_revision: Union[str, None] = 'bd2f1bb84d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
