"""docker-compose bulid

Revision ID: 3adc5ffb6c42
Revises: 78cc4ef0fbe5
Create Date: 2024-03-24 21:44:37.748890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adc5ffb6c42'
down_revision: Union[str, None] = '78cc4ef0fbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
