"""docker-compose bulid

Revision ID: 4cd0b225a6e8
Revises: 32da77ccb80d
Create Date: 2024-03-24 21:33:32.229424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd0b225a6e8'
down_revision: Union[str, None] = '32da77ccb80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
