"""docker-compose bulid

Revision ID: 61a6fc5f4b80
Revises: 3f740ec8efe2
Create Date: 2024-03-24 22:18:07.083906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a6fc5f4b80'
down_revision: Union[str, None] = '3f740ec8efe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
