"""docker-compose bulid

Revision ID: 62b1bdea2c6f
Revises: 61a6fc5f4b80
Create Date: 2024-03-24 22:22:33.115865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b1bdea2c6f'
down_revision: Union[str, None] = '61a6fc5f4b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
