"""docker-compose bulid

Revision ID: 6da2f7dd8133
Revises: 4772ce3a0337
Create Date: 2024-03-25 07:18:32.731437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da2f7dd8133'
down_revision: Union[str, None] = '4772ce3a0337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
