"""docker-compose bulid

Revision ID: 78cc4ef0fbe5
Revises: 2246aea81bfa
Create Date: 2024-03-24 21:38:21.758511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cc4ef0fbe5'
down_revision: Union[str, None] = '2246aea81bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
